[package]
name = "syncpubsub"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24.0"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "syncpubsub"
path = "src/syncpubsub.rs"
